version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: tracker_nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./cert.pem:/cert.pem:ro
      - ./cert.key:/cert.key:ro
    env_file:
      - .env
    ports:
      - 8443:8443
    restart: always
    links:
      - app

  postgres:
    image: postgres:alpine
    container_name: tracker_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    container_name: tracker_redis
    restart: always

  app:
    build: ./
    container_name: tracker_app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    env_file:
      - .env
    volumes:
      - .:/tracker
    command: python3 app.py
    restart: always
    links:
      - postgres
      - redis
volumes:
  pgdata:
