version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: tracker_nginx
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./cert.pem:/cert.pem:ro
      - ./cert.key:/cert.key:ro
    env_file:
      - .env
    ports:
      - 8443:8443
    depends_on: 
      - app

  postgres:
    image: postgres:alpine
    container_name: tracker_postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    container_name: tracker_redis
    ports:
      - 6379:6379
    restart: always

  app:
    build: ./
    container_name: tracker_app
    environment:
      - POSTGRES_HOST=tracker_postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=tracker_redis
    ports: 
      - 3001:3001
    env_file:
      - .env
    volumes:
      - .:/tracker
    command: python3 app.py
    links:
      - postgres
      - redis
volumes:
  pgdata:
